In [2]:
from transformers import pipeline

In [3]:
model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"
sentiment_classifier = pipeline(model=model_name)

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Device set to use cpu


In [6]:
text_input = "Oh, great, another large language model. Whatever!"
result = sentiment_classifier(text_input)
print(f"Sentiment analysis result: {result}")

Sentiment analysis result: [{'label': 'neutral', 'score': 0.403109073638916}]


In [7]:
text_list = ["Oh, great, another large language model. Whatever!",
             "I think this new AI agent is really different!",
             "The weather is gloomy today."]
sentiment_classifier(text_list)

[{'label': 'neutral', 'score': 0.403109073638916},
 {'label': 'positive', 'score': 0.5920102596282959},
 {'label': 'negative', 'score': 0.7665253281593323}]

In [8]:
# Zero-short text classification
model_name = "Moritzlaurer/deberta-v3-large-zeroshot-v2.0"
zero_shot_classifier = pipeline("zero-shot-classification", model=model_name)
candidate_labels = [
    "Billing Issues",
    "Technical Support",
    "Account Management",
    "General Inquiry"
]
hypothesis_template = "This text is about {}."

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/870M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

Device set to use cpu


In [9]:
customer_text = "I need help with my account password reset."
zero_shot_result = zero_shot_classifier(
    customer_text,
    candidate_labels=candidate_labels,
    hypothesis_template=hypothesis_template,
    multi_label=True
)
print(f"Zero-shot classification result: {zero_shot_result}")

Zero-shot classification result: {'sequence': 'I need help with my account password reset.', 'labels': ['Account Management', 'Technical Support', 'General Inquiry', 'Billing Issues'], 'scores': [0.8764230012893677, 0.7772998809814453, 0.04189131036400795, 6.0850405134260654e-05]}


In [11]:
# Image classification
image_classifier = pipeline("image-classification")

No model was supplied, defaulted to google/vit-base-patch16-224 and revision 3f49326 (https://huggingface.co/google/vit-base-patch16-224).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.
Device set to use cpu


In [13]:
predictions = image_classifier(["llamas.png"])
predictions

[[{'label': 'llama', 'score': 0.9988725781440735},
  {'label': 'Arabian camel, dromedary, Camelus dromedarius',
   'score': 9.834463708102703e-05},
  {'label': 'standard poodle', 'score': 4.391697439132258e-05},
  {'label': 'komondor', 'score': 3.7168701965129e-05},
  {'label': 'ram, tup', 'score': 2.7737502023228444e-05}]]

In [16]:
len(predictions[0])

5

In [17]:
predictions[0][0]

{'label': 'llama', 'score': 0.9988725781440735}

In [18]:
from transformers import AutoTokenizer
model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(model_name)

input_text = "Oh, great, another large language model. Whatever!"
encoded_input = tokenizer(input_text, return_tensors='pt')
print(f"Encoded input: {encoded_input}")

Encoded input: {'input_ids': tensor([[    0,  7516,     6,   372,     6,   277,   739,  2777,  1421,     4,
         11999,   328,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [19]:
encoded_input["input_ids"]

tensor([[    0,  7516,     6,   372,     6,   277,   739,  2777,  1421,     4,
         11999,   328,     2]])

In [24]:
tokenizer.convert_ids_to_tokens(encoded_input["input_ids"][0])

['<s>',
 'Oh',
 ',',
 'Ġgreat',
 ',',
 'Ġanother',
 'Ġlarge',
 'Ġlanguage',
 'Ġmodel',
 '.',
 'ĠWhatever',
 '!',
 '</s>']

In [25]:
tokenizer.vocab_size

50265

In [26]:
new_tokens = [
    "whaleshark",
    "unicorn",
]
tokenizer.convert_tokens_to_ids(new_tokens)

[3, 3]

In [27]:
tokenizer.convert_ids_to_tokens(3)

'<unk>'

In [28]:
tokenizer.add_tokens(new_tokens)

2

In [29]:
tokenizer.convert_tokens_to_ids("unicorn")

50266

In [30]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification
)
model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
model

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
         

In [31]:
model.roberta.embeddings

RobertaEmbeddings(
  (word_embeddings): Embedding(50265, 768, padding_idx=1)
  (position_embeddings): Embedding(514, 768, padding_idx=1)
  (token_type_embeddings): Embedding(1, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [33]:
encoded_input = tokenizer(input_text, return_tensors='pt')
embedding_tensor = model.roberta.embeddings(encoded_input['input_ids'])
embedding_tensor.shape

torch.Size([1, 13, 768])

In [34]:
embedding_tensor

tensor([[[ 0.0633, -0.0212,  0.0193,  ..., -0.0826, -0.0200, -0.0056],
         [ 0.0370,  0.1577,  0.6688,  ...,  0.0043,  0.1001,  0.2352],
         [ 0.3759,  0.0371, -0.3074,  ..., -0.6424, -0.3238,  0.0250],
         ...,
         [-0.3029,  0.1397,  0.2162,  ..., -0.0407,  0.1227, -0.4810],
         [ 0.0392, -0.1928,  0.0224,  ..., -0.3784, -0.0536, -0.1739],
         [ 0.1311, -0.0046, -0.1436,  ...,  0.2181, -0.0031, -0.2218]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
from transformers import AutoConfig
# config includes configuration details and metadata about the model
config = AutoConfig.from_pretrained(model_name)
config

RobertaConfig {
  "architectures": [
    "RobertaForSequenceClassification"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "dtype": "float32",
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "negative",
    "1": "neutral",
    "2": "positive"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label2id": {
    "negative": 0,
    "neutral": 1,
    "positive": 2
  },
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.1",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

In [ ]:
# Context manager, disable gradient calculation (used in inference to save memory and computations)
with torch.no_grad():
    outputs = model(**encoded_input) # "**"" is used to unpack the dictionary into keyword arguments
    
scores = outputs.logits[0]
probabilities = torch.softmax(scores, dim=0)
probabilities

tensor([0.3056, 0.4031, 0.2913])

In [37]:
for i, probability in enumerate(probabilities):
    label = config.id2label[i]
    print(f"{label}: {probability:.4f}")

negative: 0.3056
neutral: 0.4031
positive: 0.2913
